name: TESTE ACTION

on: [push]

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Criar arquivo
        run: |
          mkdir pasta_teste
          echo "FUNCIONOU" > pasta_teste/ok.txt
